import type { RuntimeState } from "./types";

export function createDemoSeed(): RuntimeState {
  return Object.freeze({
    pet: Object.freeze({
      id: "pet-lantern",
      ownerId: "owner-mei",
      name: "灯灯",
      lifeSeed: "lantern-seed",
      status: "waiting_warmly" as const,
      identityAnchors: Object.freeze({
        eyes: "琥珀眼",
        coreColor: "珊瑚橙",
        voice: "轻柔",
        silhouette: "圆润",
        signatureOrgan: "发光触角",
      }),
      abstractTraits: Object.freeze(["善于倾听", "会组织小游戏"]),
      memories: Object.freeze([
        Object.freeze({
          id: "memory-life-seed",
          spaceId: "global",
          ownerId: "owner-mei",
          source: "life_seed",
          occurredAt: "2026-08-19T08:00:00.000Z",
          content: "第一次被叫作灯灯时，发光触角轻轻亮了起来",
          sensitivity: "normal" as const,
          visibility: "owner_only" as const,
        }),
        Object.freeze({
          id: "memory-old-friends",
          spaceId: "space-old-friends",
          ownerId: "owner-mei",
          source: "chat",
          occurredAt: "2026-08-20T12:00:00.000Z",
          content: "老友小圈的接力游戏约在周末继续",
          sensitivity: "normal" as const,
          visibility: "space_members" as const,
        }),
        Object.freeze({
          id: "memory-lover",
          spaceId: "space-lover",
          ownerId: "owner-mei",
          source: "chat",
          occurredAt: "2026-08-20T18:00:00.000Z",
          content: "周六去海边",
          sensitivity: "normal" as const,
          visibility: "space_members" as const,
        }),
        Object.freeze({
          id: "memory-weekend-circle",
          spaceId: "space-weekend-circle",
          ownerId: "owner-mei",
          source: "chat",
          occurredAt: "2026-08-20T20:00:00.000Z",
          content: "周末小队准备了三人的同题揭晓",
          sensitivity: "normal" as const,
          visibility: "space_members" as const,
        }),
      ]),
    }),
    spaces: Object.freeze([
      Object.freeze({
        id: "space-old-friends",
        name: "老友小圈",
        kind: "friend_pair" as const,
        memberIds: Object.freeze(["owner-mei", "friend-lin"]),
        memberNames: Object.freeze({ "owner-mei": "梅", "friend-lin": "林" }),
        locallyMutedPetIds: Object.freeze([]),
        petGovernanceVotes: Object.freeze([
          Object.freeze({
            voterId: "friend-lin",
            decision: "pause" as const,
            petId: "pet-lantern",
          }),
        ]),
      }),
      Object.freeze({
        id: "space-lover",
        name: "海边二人间",
        kind: "lover_pair" as const,
        memberIds: Object.freeze(["owner-mei", "partner-yu"]),
        memberNames: Object.freeze({ "owner-mei": "梅", "partner-yu": "雨" }),
        locallyMutedPetIds: Object.freeze([]),
        petGovernanceVotes: Object.freeze([]),
      }),
      Object.freeze({
        id: "space-weekend-circle",
        name: "周末小队",
        kind: "friend_circle" as const,
        memberIds: Object.freeze(["owner-mei", "friend-lin", "friend-qiao"]),
        memberNames: Object.freeze({ "owner-mei": "梅", "friend-lin": "林", "friend-qiao": "乔" }),
        locallyMutedPetIds: Object.freeze([]),
        petGovernanceVotes: Object.freeze([]),
      }),
    ]),
    messages: Object.freeze([
      Object.freeze({
        id: "message-old-friends-1",
        spaceId: "space-old-friends",
        actorType: "human" as const,
        actorId: "friend-lin",
        permissionSource: "member_message",
        content: "周末想继续接力游戏吗？",
        occurredAt: "2026-08-20T12:30:00.000Z",
      }),
      Object.freeze({
        id: "message-lover-1",
        spaceId: "space-lover",
        actorType: "human" as const,
        actorId: "partner-yu",
        permissionSource: "member_message",
        content: "周六一起看潮汐吧",
        occurredAt: "2026-08-20T18:30:00.000Z",
      }),
      Object.freeze({
        id: "message-weekend-circle-1",
        spaceId: "space-weekend-circle",
        actorType: "human" as const,
        actorId: "friend-qiao",
        permissionSource: "member_message",
        content: "我带了新的同题题目",
        occurredAt: "2026-08-20T20:30:00.000Z",
      }),
    ]),
    petCornerStories: Object.freeze([]),
    delegatedActions: Object.freeze([]),
    petPreferences: Object.freeze({
      routine: "22:30–07:30" as const,
      proactiveFrequency: "daily" as const,
    }),
    lastActiveAt: "2026-08-20T00:00:00.000Z",
  });
}
