import { useEffect, useRef, useState } from "react";
import { AppState, Image, Pressable, Text, View } from "react-native";
import { useSession } from "../auth/SessionProvider";
import { useAppTheme } from "../theme/ThemeProvider";
import { createRequestId } from "../lib/uuid";
import { readVisionImage, visionRequest } from "./repository";
import { VisionMemoryEditor } from "./VisionMemoryEditor";
import { visionError, type VisionAsset } from "./types";
export function VisionMessageImage(props: { assetId: string; sourceMessageId?: string; onDeleted?(): void }) { const { profile } = useSession(); return profile ? <OwnedImage key={`${profile.id}:${props.assetId}`} {...props} ownerId={profile.id} /> : null; }
function OwnedImage({ assetId, ownerId, sourceMessageId, onDeleted }: { assetId: string; ownerId: string; sourceMessageId?: string; onDeleted?(): void }) {
 const { theme } = useAppTheme(); const active = useRef(true); const epoch = useRef(0); const deleteRequest = useRef(createRequestId()); const [image, setImage] = useState<{ asset: VisionAsset; url: string } | null>(null); const [notice, setNotice] = useState<string | null>(null); const [confirmDelete, setConfirmDelete] = useState(false); const [memory, setMemory] = useState(false); const [busy, setBusy] = useState(false);
 useEffect(() => { active.current = true; const load = async () => { const token = epoch.current; try { const result = await readVisionImage(ownerId, assetId); if (active.current && token === epoch.current) setImage(result); } catch { if (active.current && token === epoch.current) { setImage(null); setNotice("图片已删除或暂时无法查看。"); } } }; void load(); const timer = setInterval(() => void load(), 95_000); const listener = AppState.addEventListener("change", state => { if (state === "active") void load(); }); return () => { active.current = false; clearInterval(timer); listener.remove(); }; }, [ownerId, assetId]);
 const remove = async () => { if (!image) return; setBusy(true); try { await visionRequest(ownerId, { action: "delete", request_id: deleteRequest.current, asset_id: assetId, expected_version: image.asset.version }); if (active.current) { epoch.current++; setImage(null); setConfirmDelete(false); setMemory(false); setNotice("图片已删除，相关理解和记忆已停用。"); onDeleted?.(); } } catch (reason) { if (active.current) setNotice(visionError(reason)); } finally { if (active.current) setBusy(false); } };
 const button = (label: string, action: () => void) => <Pressable accessibilityRole="button" disabled={busy} onPress={action} style={{ minHeight: 44, paddingHorizontal: 8, justifyContent: "center" }}><Text style={{ color: theme.primary, fontSize: 12 }}>{label}</Text></Pressable>;
 return <View style={{ gap: 6 }}>{image ? <><Image accessibilityLabel="消息图片" source={{ uri: image.url }} resizeMode="contain" style={{ width: 220, height: 220, borderRadius: 8 }} onError={() => setImage(null)} /><View style={{ flexDirection: "row" }}>{sourceMessageId && image.asset.state === "active" ? button("记住图片内容", () => setMemory(true)) : null}{button("删除图片", () => setConfirmDelete(true))}</View>{confirmDelete ? <View><Text style={{ color: theme.muted, fontSize: 12 }}>删除这张图片，并停用相关理解、索引和关联私人记忆？原始文字聊天仍可回看。</Text>{button("确认删除", () => void remove())}{button("保留", () => setConfirmDelete(false))}</View> : null}{sourceMessageId ? <VisionMemoryEditor visible={memory} asset={image.asset} sourceMessageId={sourceMessageId} onClose={() => setMemory(false)} /> : null}</> : null}{notice ? <Text style={{ color: theme.muted, fontSize: 12 }}>{notice}</Text> : null}</View>;
}
