import {createClient} from "npm:@supabase/supabase-js@2";
import {generateStewardReply,resolveStewardSpace} from "../_shared/petSteward.ts";
import {TextModelAdapter} from "../_shared/modelAdapters.ts";
const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),anon=Deno.env.get("SUPABASE_ANON_KEY");
if(!url||!key||!anon||!["127.0.0.1","localhost"].includes(new URL(url).hostname))throw new Error("Isolated fixture required");
Deno.env.set("MODEL_MOCK_MODE","true");
const options={auth:{persistSession:false,autoRefreshToken:false}},service=createClient(url,key,options),users:string[]=[],spaces:string[]=[];let checks=0;
function ok(result:any):any{if(result.error)throw new Error(result.error.message);return result.data;}
function assert(condition:unknown,label:string){if(!condition)throw new Error(label);checks++;}
async function rejects(action:PromiseLike<unknown>,code:RegExp){try{await action;}catch(reason){assert(code.test(String(reason)),`expected ${code}, got ${String(reason)}`);return;}throw new Error(`expected rejection ${code}`);}
async function user(label:string){const email=`steward-${crypto.randomUUID()}@example.test`,password=`Steward-${crypto.randomUUID()}-1!`;const id=ok(await service.auth.admin.createUser({email,password,email_confirm:true})).user.id;users.push(id);ok(await service.from("profiles").insert({id,email,nickname:label}));const client=createClient(url!,anon!,options);ok(await client.auth.signInWithPassword({email,password}));return{id,client};}
async function rpc(name:string,args:any){return ok(await service.rpc(name,args));}
async function invoke(actor:any,body:any){const session=await actor.client.auth.getSession();const result=await actor.client.functions.invoke("steward-actions",{body,headers:{Authorization:`Bearer ${session.data.session.access_token}`}});if(result.error){let detail=result.error.message;try{detail=(await result.error.context.json()).error??detail;}catch{}throw new Error(detail);}return result.data;}
try{
 const A=await user("管家验收甲"),B=await user("管家验收乙");
 const pet=ok(await service.from("pets").insert({owner_id:A.id,name:"管家验收宠",personality_summary:"私人性格来源绝不进入管家模型"}).select("id,name,personality_summary").single());
 for(const name of ["管家验收一群","管家验收二群"]){const space=ok(await service.from("spaces").insert({name,kind:"friend_circle",created_by:A.id}).select("id").single());spaces.push(space.id);ok(await service.from("space_members").insert([{space_id:space.id,user_id:A.id,role:"owner"},{space_id:space.id,user_id:B.id,role:"member"}]));}
 const source=async(content:string,kind="steward",role="owner")=>ok(await service.from("pet_private_threads").insert({owner_id:A.id,pet_id:pet.id,role,conversation_kind:kind,content}).select("id").single());
 const prep=async(text:string,kind="steward",sid=spaces[0])=>{const content=`发到管家验收一群：${text}`,s=await source(content,kind);const args={p_owner:A.id,p_pet:pet.id,p_request:s.id,p_source:s.id,p_space:sid,p_exact:text};return{p:await rpc("prepare_steward_preview",args),s,args};};
 const panelRequest={action:"prepare",space_id:spaces[0],request_id:crypto.randomUUID(),exact_content:"工作台选择群后的原文。"};const panel=await invoke(A,panelRequest),panelRetry=await invoke(A,panelRequest);assert(panel.id===panelRetry.id&&panel.source_message_id===panelRetry.source_message_id,"workbench preview retry preserves one actual steward source");assert(ok(await service.from("pet_private_threads").select("conversation_kind,content").eq("id",panel.source_message_id).single()).conversation_kind==="steward"&&panel.exact_content===panelRequest.exact_content,"workbench draft preserves typed original and group scope");await rejects(invoke(A,{...panelRequest,exact_content:"替换原文"}),/steward_request_conflict/);await rejects(invoke(A,{...panelRequest,request_id:crypto.randomUUID(),space_id:crypto.randomUUID()}),/not_space_member/);await rejects(invoke(B,{...panelRequest,request_id:crypto.randomUUID()}),/steward_pet_required/);
 const initial=await prep("请带好雨伞。");assert(ok(await service.from("agent_requests").select("id").eq("requested_by",A.id)).length===0,"preview does not enqueue a request");assert(ok(await service.from("messages").select("id").eq("space_id",spaces[0])).length===0,"preview does not send a group message");
 assert((await rpc("prepare_steward_preview",initial.args)).id===initial.p.id,"preview retry returns same immutable object");
 await rejects(rpc("prepare_steward_preview",{...initial.args,p_exact:"雨伞"}),/steward_request_conflict/);
 assert(ok(await B.client.from("pet_steward_previews").select("id").eq("id",initial.p.id)).length===0,"private preview hidden from another account");
 await rejects(B.client.rpc("decide_steward_preview",{p_owner:A.id,p_preview:initial.p.id,p_request:crypto.randomUUID(),p_expected_version:1,p_action:"confirm"}).then(ok),/permission denied/);
 const body={action:"confirm",preview_id:initial.p.id,request_id:crypto.randomUUID(),expected_version:1};
 await rejects(invoke(B,body),/steward_preview_forbidden/);
 const result=await invoke(A,body),retry=await invoke(A,body);assert(result.outcome==="published"&&retry.message_id===result.message_id,"confirmation and retry return one real published message");
 const message=ok(await service.from("messages").select("*").eq("id",result.message_id).single());assert(message.text==="请带好雨伞。"&&message.sender_id===A.id&&message.delegation_confirmed_by===A.id&&Boolean(message.delegation_confirmed_at),"exact original and real attribution retained");
 assert(ok(await service.from("agent_requests").select("status,final_message_id").eq("id",result.agent_request_id).single()).status==="completed","old agent request receipt is complete only after message commit");
 assert(ok(await service.from("messages").select("id").eq("delegation_request_id",result.agent_request_id)).length===1,"retry cannot duplicate a post");
 await rejects(invoke(A,{...body,action:"dismiss"}),/steward_request_conflict/);
 await rejects(invoke(A,{...body,request_id:crypto.randomUUID()}),/steward_version_conflict/);
 const legacy=await prep("旧客户端也先预览。","legacy");assert(legacy.p.status==="pending","legacy source supports safe preview");
 const companion=await source("发到管家验收一群：错误入口","companion"),petSource=await source("发到管家验收一群：宠消息","steward","pet");
 await rejects(rpc("prepare_steward_preview",{...initial.args,p_request:companion.id,p_source:companion.id,p_exact:"错误入口"}),/steward_source_excluded/);
 await rejects(rpc("prepare_steward_preview",{...initial.args,p_request:petSource.id,p_source:petSource.id,p_exact:"宠消息"}),/steward_source_excluded/);
 const canceled=await prep("取消后不发。"),dismiss={action:"dismiss",preview_id:canceled.p.id,request_id:crypto.randomUUID(),expected_version:1};assert((await invoke(A,dismiss)).outcome==="dismissed"&&(await invoke(A,dismiss)).outcome==="dismissed","cancel is idempotent");
 await rejects(invoke(A,{...dismiss,action:"confirm",request_id:crypto.randomUUID(),expected_version:2}),/steward_preview_resolved/);
 const forgotten=await prep("遗忘后不发。" );ok(await service.from("pet_private_context_exclusions").insert({owner_id:A.id,pet_id:pet.id,message_id:forgotten.s.id}));assert(ok(await A.client.from("pet_steward_previews").select("id").eq("id",forgotten.p.id)).length===0,"forgotten preview disappears under RLS");await rejects(invoke(A,{action:"confirm",preview_id:forgotten.p.id,request_id:crypto.randomUUID(),expected_version:1}),/steward_source_excluded/);
 const changed=await prep("改写后不发。");ok(await service.from("pet_private_threads").update({content:"已改写的来源"}).eq("id",changed.s.id));await rejects(invoke(A,{action:"confirm",preview_id:changed.p.id,request_id:crypto.randomUUID(),expected_version:1}),/steward_source_changed/);
 const expired=await prep("过期后不发。");ok(await service.from("pet_steward_previews").update({expires_at:new Date(Date.now()-1000).toISOString()}).eq("id",expired.p.id));await rejects(invoke(A,{action:"confirm",preview_id:expired.p.id,request_id:crypto.randomUUID(),expected_version:1}),/steward_preview_expired/);
 const concurrent=await prep("并发只发一次。");const outcomes=await Promise.allSettled([invoke(A,{action:"confirm",preview_id:concurrent.p.id,request_id:crypto.randomUUID(),expected_version:1}),invoke(A,{action:"dismiss",preview_id:concurrent.p.id,request_id:crypto.randomUUID(),expected_version:1})]);assert(outcomes.filter(x=>x.status==="fulfilled").length===1,"confirm/cancel concurrency commits exactly one decision");
 await rejects(service.from("agent_requests").insert({space_id:spaces[0],requested_by:A.id,pet_id:pet.id,origin:"pet_private",request_kind:"delegated_message",user_input:"旧路径绕过确认",exact_content:"旧路径绕过确认",idempotency_key:`bypass:${crypto.randomUUID()}`}).then(ok),/steward_confirmation_required/);
 ok(await service.from("pet_private_context_exclusions").insert({owner_id:A.id,pet_id:pet.id,message_id:initial.s.id}));assert(Boolean(ok(await B.client.from("messages").select("id").eq("id",message.id).single())),"forgetting private source preserves shared posted message");
 const removed=await prep("删除来源后不发。");ok(await service.from("pet_private_threads").delete().eq("id",removed.s.id));assert(ok(await service.from("pet_steward_previews").select("id").eq("id",removed.p.id)).length===0,"source deletion cascades private preview");
 const left=await prep("离群后不发。","steward",spaces[1]);ok(await service.from("space_members").delete().eq("space_id",spaces[1]).eq("user_id",A.id));await rejects(invoke(A,{action:"confirm",preview_id:left.p.id,request_id:crypto.randomUUID(),expected_version:1}),/not_space_member/);ok(await service.from("space_members").insert({space_id:spaces[1],user_id:A.id,role:"owner"}));await rejects(invoke(A,{action:"confirm",preview_id:left.p.id,request_id:crypto.randomUUID(),expected_version:1}),/not_space_member/);
 // Execute the real helper with real membership/source queries, recording only synthetic model inputs.
 const adapter=new TextModelAdapter(),inputs:any[]=[];adapter.generatePetReply=async input=>{inputs.push(input);return{content:"甲说下午三点在公园集合。",concerns_owner:false,risk:"none"};};let recalls=0;
 const run=async(content:string,kind="steward",extra:any={})=>{const s=await source(content,kind);return generateStewardReply(service,{ownerId:A.id,pet,content,ownerMessageId:s.id,thread:[{id:"private",role:"owner",content:"私人经历绝不能进入群管家模型",created_at:new Date().toISOString()}],setReplyStatus:async()=>{},...extra},{adapter,recall:async(_client,input)=>{recalls++;assert(input.requiredSpaceId===spaces[0],"recall receives only explicitly named group scope");return{messages:[{actor:"[群聊回忆·管家验收一群] 甲",content:"下午三点在公园集合。"}],sources:[]};}});};
 assert(/群名/.test((await run("查一下群里之前说了什么")).content)&&recalls===0&&inputs.length===0,"no named scope means no recall or model query");
 assert(/群名/.test((await run("查管家验收一群和管家验收二群的消息")).content)&&recalls===0,"ambiguous multiple groups require clarification");
 await run("查管家验收一群之前说了什么");assert(inputs.length===1&&!JSON.stringify(inputs[0]).includes("私人"),"steward payload excludes private thread and personality sources");
 const countBefore=ok(await service.from("agent_requests").select("id").eq("requested_by",A.id)).length;const helperPreview=await run("发到管家验收一群：周六三点到。","legacy");assert(helperPreview.agentRequestId===null&&/待你确认/.test(helperPreview.content)&&ok(await service.from("agent_requests").select("id").eq("requested_by",A.id)).length===countBefore,"legacy helper creates only a preview and keeps old response contract");
 assert(resolveStewardSpace("查群里消息",[{id:"a",name:"家庭群",joinedAt:""}])===null,"a sole membership is not an implicit scope");
 const blocked=await prep("注销开始后不发。");ok(await service.rpc("block_chat_background_owner",{p_owner_id:A.id}));await rejects(invoke(A,{action:"confirm",preview_id:blocked.p.id,request_id:crypto.randomUUID(),expected_version:1}),/steward_account_deleting/);
 console.log(`PASS: ${checks} steward confirmation, isolation and legacy helper assertions.`);
}finally{for(const id of spaces)ok(await service.from("spaces").delete().eq("id",id));for(const id of users)ok(await service.auth.admin.deleteUser(id));}
