import { useCallback,useEffect,useMemo,useRef,useState } from "react";
import { ActivityIndicator,Image,Linking,Modal,Pressable,ScrollView,Switch,Text,View } from "react-native";
import { router,useFocusEffect } from "expo-router";
import { useSession } from "../auth/SessionProvider";
import { useAppTheme } from "../theme/ThemeProvider";
import { AppButton,EmptyState } from "../ui/common";
import { KeyboardScreen,KeyboardScrollView,KeyboardTextInput } from "../components/KeyboardLayout";
import { createRequestId } from "../lib/uuid";
import { isLocalDemoMode,requireSupabase } from "../lib/supabase";
import { cachedWorkItems,chooseWorkImage,getWorkDetail,pendingWork,recoverWorkCache,resolveWorkConflict,startWorkSync,submitWork,subscribeWorkData,syncWork,workOnline,WORK_CACHE_ERROR } from "./repository";
import { goalProgress,isEnded,priorityItems } from "./domain";
import { WorkItemCard } from "./WorkItemCard";
import { ReminderManager } from "../notifications/ReminderManager";
import { workKindLabel,workStatusLabel,type WorkAction,type WorkDetail,type WorkInput,type WorkItem,type WorkKind,type WorkReceipt } from "./types";

type Member={id:string;name:string};
export function WorkItemsPanel({spaceId,initialItemId}:{spaceId?:string;initialItemId?:string}){
 const {profile}=useSession();
 return profile?<ScopedWorkItemsPanel key={`${profile.id}:${spaceId??"all"}`} owner={profile.id} spaceId={spaceId} initialItemId={initialItemId}/>:null;
}
function ScopedWorkItemsPanel({owner,spaceId,initialItemId}:{owner:string;spaceId?:string;initialItemId?:string}){
 const {theme}=useAppTheme();const [items,setItems]=useState<WorkItem[]>([]);const [filter,setFilter]=useState("pending");const [loading,setLoading]=useState(true);const [error,setError]=useState("");const [offline,setOffline]=useState(false);const [selected,setSelected]=useState<string|null>(initialItemId??null);const [draft,setDraft]=useState<WorkInput|null>(null);const [forbidden,setForbidden]=useState(false);
 const alive=useRef(true);const revision=useRef(0);const [recovering,setRecovering]=useState(false);
 const refresh=useCallback(async()=>{const current=++revision.current;const valid=()=>alive.current&&current===revision.current;try{const cached=await cachedWorkItems(owner);if(!valid())return;setItems(cached);const online=await workOnline();if(!valid())return;setOffline(!online);const result=await syncWork(owner);if(!valid())return;const denied=Boolean(spaceId&&result.authorizedSpaceIds&&!result.authorizedSpaceIds.includes(spaceId));setForbidden(denied);setItems(denied?[]:result.items);setError(denied?"not_space_member":result.conflicts?"有本地修改与云端冲突，打开对应事项选择如何处理。":"");if(denied){setSelected(null);setDraft(null);}}catch(reason){if(valid()){setItems([]);setError(reason instanceof Error?reason.message:"事项加载失败");}}finally{if(valid())setLoading(false);}},[owner,spaceId]);
 useEffect(()=>{alive.current=true;const remove=subscribeWorkData(owner,()=>{void cachedWorkItems(owner).then(rows=>{if(alive.current)setItems(rows);}).catch(reason=>{if(alive.current)setError(reason instanceof Error?reason.message:"事项加载失败");});});const stop=startWorkSync(owner,()=>void refresh());return ()=>{alive.current=false;revision.current++;remove();stop();};},[owner,refresh]);
 useEffect(()=>{setSelected(initialItemId??null);},[initialItemId]);
 useFocusEffect(useCallback(()=>{void refresh();},[refresh]));
 const visible=useMemo(()=>forbidden?[]:priorityItems(items.filter(item=>(!spaceId||item.space_id===spaceId)&&(filter==="ended"?isEnded(item):!isEnded(item))&&(filter!=="personal"||!item.space_id)&&(filter!=="group"||Boolean(item.space_id))&&(filter!=="goal"||item.kind==="goal")),owner),[items,filter,spaceId,owner,forbidden]);
 return <View style={{flex:1,gap:12}}>
  <View style={{flexDirection:"row",alignItems:"center",justifyContent:"space-between",paddingHorizontal:16}}><Text style={{fontSize:22,fontWeight:"600",color:theme.text}}>{spaceId?"群事项":"事项"}</Text><AppButton label="新建" variant="quiet" disabled={forbidden} onPress={()=>setDraft({space_id:spaceId??null,kind:"task"})}/></View>
  <ScrollView horizontal showsHorizontalScrollIndicator={false} style={{flexGrow:0}} contentContainerStyle={{paddingHorizontal:16,gap:8}}>{[["pending","待处理"],["personal","个人"],["group","群事项"],["goal","目标"],["ended","已结束"]].filter(([key])=>!spaceId||!["personal","group"].includes(key)).map(([key,label])=><Pressable key={key} onPress={()=>setFilter(key)} style={{padding:10,borderRadius:theme.radius,backgroundColor:filter===key?theme.primary:theme.secondary}}><Text style={{color:filter===key?theme.onPrimary:theme.text}}>{label}</Text></Pressable>)}</ScrollView>
  {offline?<Text style={{color:theme.muted,paddingHorizontal:16}}>离线缓存 · 群权限尚未重新核实。个人修改显示待同步。</Text>:null}
  {error?<Text onPress={()=>void refresh()} style={{color:theme.danger,paddingHorizontal:16}}>{friendlyError(error)} · 点击重试</Text>:null}
  {error===WORK_CACHE_ERROR?<View style={{paddingHorizontal:16,gap:8}}><Text style={{color:theme.muted}}>重新加载前会先备份本机原数据；未同步的个人修改不会自动提交。退出登录前可联系支持恢复备份。</Text><AppButton label={recovering?"正在备份并加载…":"备份并重新加载云端事项"} disabled={recovering} onPress={()=>{setRecovering(true);void recoverWorkCache(owner).then(refresh).catch(reason=>{if(alive.current)setError(reason instanceof Error?reason.message:"重新加载失败，原数据仍保留。");}).finally(()=>{if(alive.current)setRecovering(false);});}}/></View>:null}
  <ScrollView contentContainerStyle={{padding:16,gap:12,paddingBottom:32}}>{loading&&!visible.length?<ActivityIndicator color={theme.accent}/>:null}{!loading&&!visible.length&&!error?<EmptyState icon="☷" title="这里还没有事项" body="记录一个任务，或创建目标后逐步添加阶段。日期和提醒可以留空。"/>:null}{visible.map(item=><WorkItemCard key={item.id} item={item} onOpen={setSelected}/>)}</ScrollView>
  {selected&&!forbidden?<WorkItemDetailSheet key={selected} ownerId={owner} itemId={selected} spaceId={spaceId} allItems={items} onClose={()=>setSelected(null)} onChanged={()=>void refresh()} onAddChild={(parent)=>{setSelected(null);setDraft({space_id:parent.space_id,parent_id:parent.id,kind:parent.kind==="goal"?"milestone":"task"});}} onOpen={setSelected}/>:null}
  {draft?<WorkEditor ownerId={owner} initial={draft} onClose={()=>setDraft(null)} onSaved={(item)=>{setDraft(null);setSelected(item.id);void refresh();}}/>:null}
 </View>;
}

export function friendlyError(value:string){if(/not_space_member|permission denied|row-level security/i.test(value))return "你已不在此群，或当前无权查看群事项。请返回群聊确认成员身份。";if(/unauthorized|not_authenticated|invalid jwt|jwt expired/i.test(value))return "登录已过期，请重新登录后查看事项。";const messages:Record<string,string>={work_version_conflict:"云端已有新修改，请刷新后重新确认",work_request_conflict:"同一请求的内容发生变化，请重新提交",work_forbidden:"此事项已不可用或当前无权查看",work_confirmation_expired:"确认已过期，请发起人重新调整约定",work_agreement_required:"约定尚未全部确认或负责人尚未接受",work_goal_has_uncompleted_tasks:"仍有未完成或已取消任务，请先处理目标中的任务",work_invalid_confirmation_expiry:"确认截止时间必须晚于现在并早于事项发生时间",work_participant_not_member:"相关成员已离群，请重新分配",work_owner_required:"此操作需要发起人处理",work_invalid_parent:"上级目标或阶段已结束，不能继续添加",work_already_ended:"此事项已经结束"};return messages[value]??value;}
async function membersFor(spaceId:string|undefined|null):Promise<Member[]>{if(!spaceId||isLocalDemoMode)return [];const result=await requireSupabase().from("space_members").select("user_id,profiles(nickname)").eq("space_id",spaceId).order("joined_at");if(result.error)throw result.error;return (result.data??[]).map((row:any)=>({id:row.user_id,name:row.profiles?.nickname??"群成员"}));}

export function WorkEditor({ownerId,initial,item,onClose,onSaved,onSubmit,submitLabel}:{ownerId:string;initial:WorkInput;item?:WorkItem;onClose:()=>void;onSaved:(item:WorkItem)=>void;onSubmit?:(input:WorkInput,requestId:string)=>Promise<WorkReceipt>;submitLabel?:string}){
 const {theme}=useAppTheme();const [title,setTitle]=useState(initial.title??"");const [description,setDescription]=useState(initial.description??"");const [kind,setKind]=useState<WorkKind>(initial.kind??"task");const [due,setDue]=useState(initial.due_at?new Date(initial.due_at).toLocaleString("sv-SE").slice(0,16):"");const [expiry,setExpiry]=useState(initial.terms_expires_at?new Date(initial.terms_expires_at).toLocaleString("sv-SE").slice(0,16):"");const [assignee,setAssignee]=useState(initial.assignee_id??ownerId);const [review,setReview]=useState(initial.review_required??false);const [approval,setApproval]=useState(initial.approval??"none");const [participants,setParticipants]=useState<string[]>(initial.participants??[]);const [members,setMembers]=useState<Member[]>([]);const [busy,setBusy]=useState(false);const [error,setError]=useState("");
 useEffect(()=>{let active=true;void membersFor(initial.space_id).then(rows=>{if(active)setMembers(rows);}).catch(reason=>{if(active)setError(friendlyError(reason?.message??"群成员暂时无法加载"));});return ()=>{active=false;};},[initial.space_id]);
 const submission=useRef<{payload:string;id:string}|null>(null);
 const inputStyle={backgroundColor:theme.secondary,color:theme.text,borderRadius:theme.radius,padding:12,minHeight:48};
 const date=(value:string)=>{if(!value.trim())return null;const parsed=new Date(value.trim().replace(" ","T"));if(Number.isNaN(parsed.valueOf()))throw new Error("请输入有效日期，例如 2026-09-12 09:00");return parsed.toISOString();};
 const save=async()=>{if(busy)return;setBusy(true);try{const input:WorkInput={title:title.trim(),description,due_at:date(due),...(initial.space_id?{assignee_id:kind==="task"&&approval!=="majority"?assignee:null,participants}:{}),...(expiry?{terms_expires_at:date(expiry)}:{})};
   if(!item)Object.assign(input,{kind,space_id:initial.space_id??null,parent_id:initial.parent_id??null,approval,review_required:review});
   const payload=JSON.stringify({input,itemId:item?.id,version:item?.version});if(submission.current?.payload!==payload)submission.current={payload,id:createRequestId()};
   const result=onSubmit?await onSubmit(input,submission.current.id):await submitWork(ownerId,{action:item?"edit":"create",request_id:submission.current.id,item_id:item?.id,expected_version:item?.version,input});onSaved(result.item);
 }catch(reason){setError(friendlyError(reason instanceof Error?reason.message:"保存失败"));}finally{setBusy(false);}};
 return <Modal visible transparent animationType="slide" onRequestClose={onClose}><KeyboardScreen style={{flex:1,justifyContent:"flex-end",backgroundColor:theme.overlay}}><View style={{maxHeight:"94%",backgroundColor:theme.card,borderTopLeftRadius:theme.radius+8,borderTopRightRadius:theme.radius+8}}><KeyboardScrollView contentContainerStyle={{padding:20,gap:14}}>
  <Text style={{color:theme.text,fontSize:20,fontWeight:"600"}}>{item?"编辑事项":initial.space_id?"拟定群安排":"新建个人事项"}</Text>
  {!item&&!initial.parent_id?<View style={{flexDirection:"row",gap:8}}>{(["task","goal"] as WorkKind[]).map(value=><AppButton key={value} variant={kind===value?"primary":"quiet"} label={workKindLabel[value]} onPress={()=>setKind(value)}/>)}</View>:null}
  <Text style={{color:theme.muted}}>标题</Text><KeyboardTextInput accessibilityLabel="事项标题" value={title} onChangeText={setTitle} maxLength={200} placeholder="想推进什么事" placeholderTextColor={theme.muted} style={inputStyle}/>
  <Text style={{color:theme.muted}}>说明与交付要求</Text><KeyboardTextInput accessibilityLabel="事项说明" value={description} onChangeText={setDescription} maxLength={4000} multiline style={[inputStyle,{minHeight:90}]}/>
  <Text style={{color:theme.muted}}>截止日期（可留空；当前设备时区）</Text><KeyboardTextInput accessibilityLabel="截止日期" value={due} onChangeText={setDue} placeholder="2026-09-12 09:00" placeholderTextColor={theme.muted} style={inputStyle}/>
  {initial.space_id?<>
   {!item?<View style={{gap:8}}><Text style={{color:theme.muted}}>约定方式</Text>{[["none","分工，由负责人接受"],["all","共同时间，相关成员全部同意"],["majority","普通方案，发布时成员过半数通过"]].filter(([value])=>kind!=="task"||value!=="majority").map(([value,label])=><AppButton key={value} label={label} variant={approval===value?"primary":"quiet"} onPress={()=>{setApproval(value as typeof approval);if(value==="majority")setParticipants([]);}}/>)}</View>:null}
   {kind==="task"?<><Text style={{color:theme.muted}}>负责人（接受后才形成承诺）</Text><View style={{flexDirection:"row",flexWrap:"wrap",gap:8}}>{members.map(member=><AppButton key={member.id} label={member.id===ownerId?`${member.name}（我）`:member.name} variant={assignee===member.id?"primary":"quiet"} onPress={()=>setAssignee(member.id)}/>)}</View></>:null}
   {approval==="all"?<><Text style={{color:theme.muted}}>需要安排的成员</Text><View style={{flexDirection:"row",flexWrap:"wrap",gap:8}}>{members.map(member=><AppButton key={member.id} label={member.name} variant={participants.includes(member.id)?"primary":"quiet"} onPress={()=>setParticipants(old=>old.includes(member.id)?old.filter(id=>id!==member.id):[...old,member.id])}/>)}</View></>:null}
   {!item&&kind==="task"?<View style={{flexDirection:"row",justifyContent:"space-between",alignItems:"center"}}><Text style={{color:theme.text}}>完成后由发起人验收</Text><Switch value={review} onValueChange={setReview}/></View>:null}
   <Text style={{color:theme.muted}}>确认有效期（默认 48 小时，早于事项发生时间）</Text><KeyboardTextInput accessibilityLabel="确认有效期" value={expiry} onChangeText={setExpiry} placeholder="可留空" placeholderTextColor={theme.muted} style={inputStyle}/>
   <Text style={{color:theme.muted,lineHeight:20}}>{item?.publication==="published"?"调整截止时间、负责人或交付要求后，需要重新确认约定。":"保存后先预览内容，确认发布才会请相关成员回应。"}</Text>
  </>:<Text style={{color:theme.muted}}>截止日期与提醒分开；这里不会自动安排提醒。</Text>}
  {onSubmit?<Text style={{color:theme.muted}}>上方是将发布的完整安排。确认后署名“异宠代本人发布 · 本人已确认”，相关成员仍需同意并接受责任。</Text>:null}
  {error?<Text style={{color:theme.danger}}>{error}</Text>:null}<AppButton label={busy?"正在保存…":submitLabel??(item?"保存修改":initial.space_id?"保存并预览":"创建事项")} disabled={busy||!title.trim()||approval==="all"&&!participants.length} onPress={()=>void save()}/><AppButton label="关闭" variant="quiet" onPress={onClose}/>
 </KeyboardScrollView></View></KeyboardScreen></Modal>;
}

export function WorkItemDetailSheet({ownerId,itemId,spaceId,allItems=[],onClose,onChanged,onAddChild,onOpen}:{ownerId:string;itemId:string;spaceId?:string;allItems?:WorkItem[];onClose:()=>void;onChanged?:()=>void;onAddChild?:(parent:WorkItem)=>void;onOpen?:(id:string)=>void}){
 const {theme}=useAppTheme();const [detail,setDetail]=useState<WorkDetail|null>(null);const [error,setError]=useState("");const [busy,setBusy]=useState(false);const [editing,setEditing]=useState(false);const [note,setNote]=useState("");const [link,setLink]=useState("");const [members,setMembers]=useState<Member[]>([]);const [conflict,setConflict]=useState<{local:WorkItem;server?:WorkItem}|null>(null);
 const loadRevision=useRef(0);
 const load=useCallback(async()=>{const current=++loadRevision.current;try{const data=await getWorkDetail(ownerId,itemId);if(spaceId&&data.item.space_id!==spaceId)throw new Error("此事项不属于当前群，请从对应群聊或事项列表打开。");const nextMembers=await membersFor(data.item.space_id);const queue=await pendingWork(ownerId);if(current!==loadRevision.current)return;setDetail(data);setError("");setMembers(nextMembers);const conflicts=queue.filter(p=>p.local.id===itemId&&p.state==="conflict");setConflict(conflicts.length?conflicts.at(-1)!:null);}catch(reason){if(current===loadRevision.current){setDetail(null);setError(friendlyError(reason instanceof Error?reason.message:"加载失败"));}}},[ownerId,itemId,spaceId]);
 useEffect(()=>{setDetail(null);setEditing(false);setNote("");setLink("");void load();const remove=subscribeWorkData(ownerId,()=>void load());return ()=>{loadRevision.current++;remove();};},[load,ownerId]);
 const item=detail?.item;const owner=item?.owner_id===ownerId;const assignee=item?.assignee_id===ownerId;const currentVotes=detail?.confirmations.filter(v=>v.terms_version===item?.terms_version)??[];const mine=currentVotes.find(v=>v.user_id===ownerId);const name=(id:string|null)=>members.find(member=>member.id===id)?.name??(id===ownerId?"我":id?"原成员":"未分配");
 const act=async(action:WorkAction,input:WorkInput={})=>{if(!item||busy)return;setBusy(true);try{await submitWork(ownerId,{action,request_id:createRequestId(),item_id:item.id,expected_version:item.version,input});setNote("");setLink("");await load();onChanged?.();}catch(reason){setError(friendlyError(reason instanceof Error?reason.message:"操作失败"));}finally{setBusy(false);}};
 const progress=item&&item.kind!=="task"?goalProgress(item.id,allItems):null;
 const fieldStyle={backgroundColor:theme.secondary,color:theme.text,borderRadius:theme.radius,padding:12,minHeight:48};
 return <Modal visible transparent animationType="slide" onRequestClose={onClose}><KeyboardScreen style={{flex:1,justifyContent:"flex-end",backgroundColor:theme.overlay}}><View style={{maxHeight:"96%",backgroundColor:theme.card,borderTopLeftRadius:theme.radius+8,borderTopRightRadius:theme.radius+8}}><KeyboardScrollView contentContainerStyle={{padding:20,gap:14}}>
  {!detail&&!error?<ActivityIndicator color={theme.accent}/>:null}
  {item?<><Text style={{color:theme.text,fontSize:22,fontWeight:"600"}}>{item.title}</Text><Text style={{color:theme.muted}}>{item.publication==="draft"?"等待本人预览发布":workStatusLabel[item.status]} · {workKindLabel[item.kind]}{item.sync_state?" · 待同步":""}</Text>
   {item.description?<Text style={{color:theme.text,lineHeight:22}}>{item.description}</Text>:null}<Text style={{color:theme.muted}}>截止：{item.due_at?new Date(item.due_at).toLocaleString("zh-CN"):"未设置"}</Text>
   {item.space_id?<><Text style={{color:theme.muted}}>发起人：{name(item.owner_id)}{item.kind==="task"?` · 负责人：${name(item.assignee_id)}`:""}</Text><Text style={{color:theme.muted}}>完成方式：{item.review_required?"发起人验收":"负责人自报完成"}</Text>{item.publication==="published"?<Text style={{color:theme.muted}}>异宠代{name(item.owner_id)}发布 · 本人已确认</Text>:null}
    {item.status==="pending_acceptance"?<><Text style={{color:theme.muted}}>确认期限：{item.terms_expires_at?new Date(item.terms_expires_at).toLocaleString("zh-CN"):"未设置"}。未回应不算同意。</Text>{!item.terms_valid?<Text style={{color:theme.danger}}>约定已失效，需要发起人重新分配。</Text>:null}{currentVotes.map(v=><Text key={v.user_id} style={{color:theme.text}}>{name(v.user_id)}：{{pending:"待回应",agreed:"已同意",declined:"已拒绝",invalidated:"已离群，确认失效"}[v.decision]}</Text>)}</>:null}
   </>:null}
   {item.sync_state?<Text style={{color:theme.accent}}>个人修改待同步；云端原提醒尚未改变。</Text>:null}
   {progress?<Text style={{color:theme.muted}}>任务完成 {progress.completed}/{progress.total} · {progress.percent}%{progress.cancelled?` · 已取消 ${progress.cancelled}`:""}</Text>:null}
   {conflict?<View style={{gap:10,padding:12,backgroundColor:theme.secondary,borderRadius:theme.radius}}><Text style={{color:theme.danger}}>云端已有其他修改，本地内容仍保留</Text><Text selectable style={{color:theme.text}}>本地：{conflict.local.title} · {conflict.local.description} · {workStatusLabel[conflict.local.status]}</Text><Text selectable style={{color:theme.muted}}>云端：{conflict.server?`${conflict.server.title} · ${conflict.server.description} · ${workStatusLabel[conflict.server.status]}`:"事项已不可用"}</Text>{([['keep_server','采用云端'],['apply_local','以当前云端版本重新提交本地修改']] as const).map(([choice,label])=><AppButton key={choice} label={label} variant="quiet" disabled={busy||choice==='apply_local'&&!conflict.server} onPress={()=>{setBusy(true);void resolveWorkConflict(ownerId,item.id,choice).then(()=>syncWork(ownerId)).then(load).catch(reason=>setError(friendlyError(String(reason.message)))).finally(()=>setBusy(false));}}/>)}</View>:null}
   {!isEnded(item)&&!conflict?<>
    {owner?<AppButton label="编辑事项" variant="quiet" disabled={busy} onPress={()=>setEditing(true)}/>:null}
    {owner&&item.publication==="draft"?<><Text style={{color:theme.muted}}>请确认上方完整安排。发布后署名“异宠代{name(item.owner_id)}发布 · 本人已确认”，再由相关成员同意及负责人接受。</Text><AppButton label="本人确认，发布安排" disabled={busy} onPress={()=>void act("publish",{confirmed:true})}/></>:null}
    {item.space_id&&item.publication==="published"&&item.status==="pending_acceptance"&&item.terms_valid?<>
     {assignee?<View style={{gap:8}}><AppButton label="接受任务" disabled={busy} onPress={()=>void act("accept")}/><AppButton label="拒绝，交回发起人处理" disabled={busy} variant="quiet" onPress={()=>void act("reject")}/></View>:null}
     {mine?.decision==="pending"&&!assignee?<View style={{gap:8}}><AppButton label="同意当前约定" disabled={busy} onPress={()=>void act("confirm")}/><AppButton label="不同意" disabled={busy} variant="quiet" onPress={()=>void act("decline")}/></View>:null}
    </>:null}
    {(assignee||owner&&item.kind!=="task")&&["not_started","in_progress"].includes(item.status)?<><KeyboardTextInput accessibilityLabel="进度或完成说明" value={note} onChangeText={setNote} multiline maxLength={4000} placeholder="进度或完成说明（可选）" placeholderTextColor={theme.muted} style={[fieldStyle,{minHeight:80}]}/><AppButton label="更新进度" variant="quiet" disabled={busy} onPress={()=>void act("progress",{completion_note:note})}/><AppButton label={item.review_required?"提交完成，等待验收":"标记完成"} disabled={busy||Boolean(progress&&!progress.canComplete)} onPress={()=>void act("complete",{completion_note:note})}/></>:null}
    {owner&&item.status==="pending_review"?<><AppButton label="验收通过" disabled={busy} onPress={()=>void act("review",{approved:true})}/><AppButton label="退回继续处理" variant="quiet" disabled={busy} onPress={()=>void act("review",{approved:false})}/></>:null}
    {owner&&item.kind!=="task"&&onAddChild?<AppButton label={item.kind==="goal"?"添加阶段":"添加任务"} variant="quiet" onPress={()=>onAddChild(item)}/>:null}
    {owner?<AppButton label="取消此事项" disabled={busy} variant="quiet" onPress={()=>void act("cancel")}/>:null}
   </>:null}
   {item.completion_note?<Text style={{color:theme.text,lineHeight:22}}>进度 / 完成说明：{item.completion_note}</Text>:null}
   {detail.children.map(child=><WorkItemCard key={child.id} item={child} onOpen={onOpen}/>)}
   <Text style={{color:theme.text,fontWeight:"600"}}>材料与来源</Text>
   {detail.materials.length===0?<Text style={{color:theme.muted}}>可添加文字说明、链接、图片或聊天来源。</Text>:null}
   {detail.materials.map(material=><View key={material.id} style={{gap:6}}>{material.kind==="image"&&material.url?<Image source={{uri:material.url}} accessibilityLabel="事项图片材料" style={{width:"100%",height:220,borderRadius:theme.radius}} resizeMode="contain"/>:<Text selectable style={{color:theme.text,lineHeight:22}} onPress={material.kind==="link"&&/^https?:\/\//i.test(material.content)?()=>void Linking.openURL(material.content):undefined}>{material.content}</Text>}{material.kind==="message"&&material.source_message_id&&item.space_id?<AppButton label="查看来源消息" variant="quiet" onPress={()=>{onClose();router.push({pathname:"/chat/[spaceId]",params:{spaceId:item.space_id!,messageId:material.source_message_id!}});}}/>:null}{material.is_completion?<Text style={{color:theme.muted}}>完成材料</Text>:null}</View>)}
   {(owner||assignee)&&!conflict?<><KeyboardTextInput accessibilityLabel="材料链接或文字" value={link} onChangeText={setLink} maxLength={4000} multiline placeholder="粘贴链接或补充文字说明" placeholderTextColor={theme.muted} style={fieldStyle}/><AppButton label="添加材料" variant="quiet" disabled={busy||!link.trim()||Boolean(item.sync_state)} onPress={()=>void act("attach",{material:{kind:/^https?:\/\//i.test(link.trim())?"link":"note",content:link.trim(),is_completion:["completed","pending_review"].includes(item.status)}})}/><AppButton label="添加图片" variant="quiet" disabled={busy||Boolean(item.sync_state)} onPress={()=>{setBusy(true);void chooseWorkImage(ownerId,item,["completed","pending_review"].includes(item.status)).then(load).catch(reason=>setError(friendlyError(reason.message))).finally(()=>setBusy(false));}}/></>:null}
   {(owner||assignee||item.participants.includes(ownerId))&&item.publication==="published"&&!item.sync_state?<><Text style={{color:theme.muted}}>以下提醒只通知你本人，截止时间不会自动产生提醒。</Text><ReminderManager itemId={item.id} title={item.title}/></>:null}
  </>:null}
  {error?<Text selectable style={{color:theme.danger}}>{error}</Text>:null}<AppButton label="关闭" variant="quiet" onPress={onClose}/>
 </KeyboardScrollView></View></KeyboardScreen>{editing&&item?<WorkEditor ownerId={ownerId} initial={item} item={item} onClose={()=>setEditing(false)} onSaved={()=>{setEditing(false);void load();onChanged?.();}}/>:null}</Modal>;
}
