import { Redirect } from "expo-router";
import { useCallback, useEffect, useMemo, useState } from "react";
import { ActivityIndicator, FlatList, Image, Modal, Platform, Pressable, ScrollView, StyleSheet, Text, TextInput, type TextInputKeyPressEvent, View } from "react-native";
import { useSafeAreaInsets } from "react-native-safe-area-context";
import { useSession } from "../../src/auth/SessionProvider";
import { GenerativePetPreview } from "../../src/components/GenerativePetPreview";
import { createPetRepository } from "../../src/data/petRepository";
import type { PetEvolutionEvent, PetExperience, PetGenerationSession, PetPrivateMessage, PetRecord, PetVisualAsset, StyleSignal } from "../../src/data/types";
import { MIN_INCUBATION_TURNS } from "../../src/pets/rules";
import { AppButton, DemoBanner, Surface } from "../../src/ui/common";
import { colors, radii, spacing } from "../../src/theme/tokens";

function CandidateVisual({ asset, url, size = 250 }: Readonly<{ asset: PetVisualAsset; url?: string | null; size?: number }>) {
  return asset.storagePath.startsWith("local-") ? <GenerativePetPreview seed={asset.storagePath} size={size} /> : url ? <Image source={{ uri: url }} style={{ width: size, height: size, borderRadius: 28 }} /> : <ActivityIndicator color={colors.mint} />;
}

function SignalCard({ signal, onFeedback, onCorrect }: Readonly<{ signal: StyleSignal; onFeedback(kind: "accepted" | "forgotten"): void; onCorrect(): void }>) {
  return <Surface style={[styles.signal, signal.feedback === "forgotten" && styles.forgotten]}><View style={styles.signalHead}><Text style={styles.signalTitle}>{signal.tendency}</Text><Text style={styles.confidence}>{Math.round(signal.confidence * 100)}%</Text></View><Text style={styles.signalBody}>{signal.rationale}</Text><Text style={styles.signalSource}>来源：{signal.sourceLabel} · {new Date(signal.createdAt).toLocaleDateString("zh-CN")}</Text><Text style={styles.signalImpact}>可能影响：异宠之后的措辞、动作与外观倾向；不会直接规定终态。</Text><View style={styles.signalActions}><Pressable onPress={() => onFeedback("accepted")}><Text style={[styles.signalAction, signal.feedback === "accepted" && styles.signalActionActive]}>认可</Text></Pressable><Pressable onPress={onCorrect}><Text style={[styles.signalAction, signal.feedback === "corrected" && styles.signalActionActive]}>纠正</Text></Pressable><Pressable onPress={() => onFeedback("forgotten")}><Text style={styles.forget}>忘记</Text></Pressable></View></Surface>;
}

export default function PetRoute() {
  const { profile, isLocalDemo } = useSession(); const insets = useSafeAreaInsets(); const repository = useMemo(() => profile ? createPetRepository(profile) : null, [profile]);
  const [pet, setPet] = useState<PetRecord | null>(null); const [messages, setMessages] = useState<readonly PetPrivateMessage[]>([]); const [assets, setAssets] = useState<readonly PetVisualAsset[]>([]); const [signals, setSignals] = useState<readonly StyleSignal[]>([]);
  const [experiences, setExperiences] = useState<readonly PetExperience[]>([]); const [events, setEvents] = useState<readonly PetEvolutionEvent[]>([]);
  const [generationSessions, setGenerationSessions] = useState<readonly PetGenerationSession[]>([]);
  const [name, setName] = useState(""); const [chat, setChat] = useState(""); const [instruction, setInstruction] = useState("更像一个会观察人的奇异生命"); const [selectedAssetId, setSelectedAssetId] = useState<string | null>(null); const [urls, setUrls] = useState<Record<string, string>>({});
  const [loading, setLoading] = useState(true); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null); const [confirming, setConfirming] = useState(false);
  const [correcting, setCorrecting] = useState<StyleSignal | null>(null); const [correction, setCorrection] = useState(""); const [evolving, setEvolving] = useState(false); const [blessing, setBlessing] = useState("");

  const load = useCallback(async () => {
    if (!repository) return; try { const [nextPet, nextMessages, nextAssets, nextSignals, nextExperiences, nextEvents, nextGenerations] = await Promise.all([repository.getPet(), repository.listPrivateMessages(), repository.listAssets(), repository.listStyleSignals(), repository.listExperiences(), repository.listEvolutionEvents(), repository.listGenerationSessions()]); setPet(nextPet); setMessages(nextMessages); setAssets(nextAssets); setSignals(nextSignals); setExperiences(nextExperiences); setEvents(nextEvents); setGenerationSessions(nextGenerations); setSelectedAssetId(nextPet?.status === "confirmed" ? nextPet.currentAssetId : nextAssets.at(-1)?.id ?? null); setError(null); }
    catch (reason) { setError(reason instanceof Error ? reason.message : "异宠档案加载失败"); } finally { setLoading(false); }
  }, [repository]);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => repository?.subscribe(() => void load()), [load, repository]);
  useEffect(() => { for (const asset of assets) { if (asset.storagePath.startsWith("local-") || urls[asset.storagePath]) continue; void repository?.createSignedAssetUrl(asset.storagePath).then((url) => setUrls((current) => ({ ...current, [asset.storagePath]: url }))); } }, [assets, repository, urls]);
  if (!profile || !repository) return <Redirect href="/login" />;
  const selected = assets.find((asset) => asset.id === selectedAssetId) ?? null;
  const act = async (operation: () => Promise<void>) => { setBusy(true); setError(null); try { await operation(); await load(); } catch (reason) { setError(reason instanceof Error ? reason.message : "操作失败"); } finally { setBusy(false); } };
  const create = () => act(async () => { await repository.createPet(name.trim()); });
  const sendChat = () => act(async () => { const content = chat.trim(); if (!content) return; setChat(""); await repository.chat(content); });
  const generate = (explore = false) => act(async () => { await repository.generateCandidate(instruction.trim(), explore ? null : selectedAssetId, explore); });
  const confirm = () => act(async () => { if (!selectedAssetId) return; await repository.confirmPet(selectedAssetId); setConfirming(false); });
  const evolve = () => act(async () => { await repository.evolve({ blessing: blessing.trim() }); setEvolving(false); setBlessing(""); });
  const repair = (eventId: string) => act(async () => { await repository.evolve({ eventId, continuityRepair: true }); });
  const latestGeneration = generationSessions[0] ?? null;
  const generationActive = latestGeneration?.status === "queued" || latestGeneration?.status === "running";
  const evolutionActive = events.some((event) => event.status === "queued" || event.status === "running");
  const handleChatKeyPress = (event: TextInputKeyPressEvent) => {
    if (Platform.OS !== "web" || event.nativeEvent.key !== "Enter") return;
    const nativeEvent = event.nativeEvent as typeof event.nativeEvent & { isComposing?: boolean; keyCode?: number; shiftKey?: boolean };
    const shiftKey = (event as unknown as { shiftKey?: boolean }).shiftKey ?? nativeEvent.shiftKey;
    if (shiftKey || nativeEvent.isComposing || nativeEvent.keyCode === 229) return;
    event.preventDefault();
    if (chat.trim() && !busy) void sendChat();
  };

  if (loading) return <View style={styles.center}><ActivityIndicator color={colors.coral} /></View>;
  return (
    <ScrollView style={styles.page} contentContainerStyle={[styles.content, { paddingTop: insets.top + spacing.md }]} keyboardShouldPersistTaps="handled">
      {isLocalDemo ? <DemoBanner /> : null}<View><Text style={styles.eyebrow}>ONE PET / 一生一只</Text><Text style={styles.title}>{pet ? pet.name : "孵化你的异宠"}</Text></View>
      {error ? <Pressable onPress={() => setError(null)} style={styles.error}><Text style={styles.errorText}>{error}</Text></Pressable> : null}
      {latestGeneration && (generationActive || latestGeneration.status === "failed") ? <Surface style={styles.taskCard}><View style={styles.taskHead}><View><Text style={styles.sectionTitle}>{generationActive ? "异宠外观正在生成" : "这次外观生成失败"}</Text><Text style={styles.copy}>{latestGeneration.status === "queued" ? "已排队，可以离开页面，完成后会自动出现。" : latestGeneration.status === "running" ? `正在连接图像模型 · 第 ${latestGeneration.attempts || 1} 次尝试` : `原因：${latestGeneration.errorCode ?? "模型暂时不可用"}`}</Text></View>{generationActive ? <ActivityIndicator color={colors.coral} /> : null}</View>{latestGeneration.status === "failed" && latestGeneration.attempts < 2 ? <AppButton label="用同一任务重试" variant="quiet" disabled={busy} onPress={() => void act(() => repository.retryGeneration(latestGeneration.id).then(() => undefined))} /> : null}</Surface> : null}
      {!pet ? <Surface style={styles.naming}><Text style={styles.sectionTitle}>先给胚胎一个名字</Text><Text style={styles.copy}>名字确认后仍属于同一只异宠。外观在正式确认前可以反复沟通和修改。</Text><TextInput value={name} onChangeText={setName} maxLength={24} placeholder="例如：芽芽" placeholderTextColor={colors.textMuted} style={styles.input} /><AppButton label={busy ? "正在唤醒…" : "开始对话"} disabled={busy || !name.trim()} onPress={create} /></Surface> : (
        <>
          {pet.status === "incubating" ? <Surface style={styles.stage}><Text style={styles.stageLabel}>孵化对话</Text><Text style={styles.stageTitle}>先让它从你的表达里认识你</Text><View style={styles.progressTrack}><View style={[styles.progressFill, { width: `${Math.min(100, pet.conversationTurns / MIN_INCUBATION_TURNS * 100)}%` }]} /></View><Text style={styles.progressText}>{pet.conversationTurns} / {MIN_INCUBATION_TURNS} 轮 · 达到 5 轮后才能生成第一张候选</Text></Surface> : null}
          {pet.status === "drafting" && selected ? <Surface style={styles.visualCard}><View style={styles.visualHeader}><View><Text style={styles.stageLabel}>尚未确认 · 可自由修改</Text><Text style={styles.stageTitle}>这是当前草稿，不是最终承诺</Text></View><Text style={styles.quota}>今日剩余 {pet.generationsRemainingToday}</Text></View><View style={styles.visual}><CandidateVisual asset={selected} url={urls[selected.storagePath]} /></View><FlatList horizontal data={assets} keyExtractor={(item) => item.id} showsHorizontalScrollIndicator={false} contentContainerStyle={styles.candidates} renderItem={({ item, index }) => <Pressable onPress={() => setSelectedAssetId(item.id)} style={[styles.candidate, selectedAssetId === item.id && styles.candidateSelected]}><CandidateVisual asset={item} url={urls[item.storagePath]} size={74} /><Text style={styles.candidateLabel}>候选 {index + 1}</Text></Pressable>} /><TextInput value={instruction} onChangeText={setInstruction} multiline placeholder="用自然语言继续修改，例如：不要这么可爱" placeholderTextColor={colors.textMuted} style={[styles.input, styles.instruction]} /><View style={styles.buttonRow}><View style={styles.flex}><AppButton label={generationActive ? "后台生成中…" : busy ? "正在提交…" : "基于当前修改"} disabled={busy || generationActive || !instruction.trim()} onPress={() => void generate(false)} /></View><View style={styles.flex}><AppButton label="重新探索方向" variant="secondary" disabled={busy || generationActive || !instruction.trim()} onPress={() => void generate(true)} /></View></View><AppButton label="选择这张并确认" variant="quiet" disabled={busy || generationActive} onPress={() => setConfirming(true)} /></Surface> : null}
          {pet.status === "confirmed" && selected ? <Surface style={styles.confirmed}><Text style={styles.stageLabel}>已确认 · 同一生命继续成长</Text><View style={styles.visual}><CandidateVisual asset={selected} url={urls[selected.storagePath]} /></View><Text style={styles.stageTitle}>它不会再回到初始捏宠</Text><Text style={styles.copy}>以后所有外观变化都来自相处与重大进化。进化会引用父图保持生命连续，但不锁死眼睛、颜色、轮廓或器官。</Text><View style={styles.lineage}><Text style={styles.lineageText}>形态谱系 · 第 {assets.filter((asset) => !asset.isDraft).length || 1} 个生命阶段</Text></View>{evolutionActive ? <View style={styles.taskInline}><ActivityIndicator color={colors.coral} /><Text style={styles.copy}>正在进入下一生命阶段，可以先离开页面。</Text></View> : events[0]?.status === "failed" ? <View style={styles.taskInline}><Text style={styles.errorText}>进化失败：{events[0].errorCode ?? "图像模型暂时不可用"}</Text><AppButton label="沿用同一事件重试" variant="quiet" disabled={busy || events[0].failedAttempts >= 2} onPress={() => void act(() => repository.evolve({ eventId: events[0].id }).then(() => undefined))} /></View> : null}<View style={styles.experienceList}><Text style={styles.sectionTitle}>最近相处经历</Text>{experiences.length ? experiences.slice(0, 3).map((experience) => <View key={experience.id} style={styles.experience}><Text style={styles.experienceText}>{experience.summary}</Text><Text style={styles.signalSource}>{new Date(experience.occurredAt).toLocaleString("zh-CN")}</Text></View>) : <Text style={styles.copy}>先和它私聊，或在关系空间的宠物角照顾它；真实相处会成为下一次进化的原因。</Text>}</View><AppButton label={evolutionActive ? "正在长大…" : "送上祝福，开启重大进化"} disabled={busy || evolutionActive || !experiences.length} onPress={() => setEvolving(true)} />{events[0]?.status === "succeeded" && events[0].officialAssetId === pet.currentAssetId && !events[0].continuityRepairUsed ? <AppButton label="报告：与上一形态完全断裂" variant="quiet" disabled={busy || evolutionActive} onPress={() => void repair(events[0].id)} /> : null}<Text style={styles.repairNote}>连续性修复只会沿用同一事件重试一次，不能借此重新捏宠。</Text></Surface> : null}
          {pet.status !== "confirmed" && pet.conversationTurns >= MIN_INCUBATION_TURNS && pet.status === "incubating" ? <Surface style={styles.ready}><Text style={styles.sectionTitle}>第一版性格判断已经可以形成</Text><Text style={styles.copy}>系统会综合这 5 轮对话生成，不套固定“萌宠、赛博或水彩”画风。</Text><TextInput value={instruction} onChangeText={setInstruction} multiline style={[styles.input, styles.instruction]} placeholderTextColor={colors.textMuted} /><AppButton label={generationActive ? "后台生成中…" : busy ? "正在提交…" : "生成第一张候选"} disabled={busy || generationActive} onPress={() => void generate(false)} /></Surface> : null}
          <Surface style={styles.chatCard}><View style={styles.chatHead}><Text style={styles.sectionTitle}>和 {pet.name} 私聊</Text><Text style={styles.private}>仅主人可见</Text></View><View style={styles.thread}>{messages.slice(-10).map((message) => <View key={message.id} style={[styles.privateMessage, message.role === "owner" ? styles.ownerMessage : styles.petMessage]}><Text style={[styles.privateText, message.role === "owner" && styles.ownerText]}>{message.content}</Text></View>)}</View><View style={styles.chatComposer}><TextInput value={chat} onChangeText={setChat} onKeyPress={handleChatKeyPress} onSubmitEditing={sendChat} multiline submitBehavior={Platform.OS === "web" ? "newline" : "submit"} returnKeyType="send" placeholder={pet.status === "confirmed" ? "通过相处继续培养它…" : "说说你喜欢怎样相处…"} placeholderTextColor={colors.textMuted} style={styles.chatInput} /><Pressable disabled={busy || !chat.trim()} onPress={sendChat} style={[styles.chatSend, (busy || !chat.trim()) && styles.disabled]}><Text style={styles.chatSendText}>发送</Text></Pressable></View></Surface>
          <View style={styles.signalSection}><Text style={styles.sectionTitle}>我观察到的倾向</Text><Text style={styles.copy}>只展示概括性依据，不展示其他成员私密原文。遗忘后，该信号不再进入后续模型提示词。</Text>{signals.length ? signals.map((signal) => <SignalCard key={signal.id} signal={signal} onFeedback={(kind) => void act(() => repository.feedback(signal.id, kind))} onCorrect={() => { setCorrecting(signal); setCorrection(signal.tendency); }} />) : <Surface><Text style={styles.copy}>继续相处后，这里会出现可以认可、纠正或忘记的成长札记。</Text></Surface>}</View>
        </>
      )}
      {busy ? <ActivityIndicator color={colors.coral} /> : null}
      <Modal transparent visible={confirming} animationType="fade" onRequestClose={() => setConfirming(false)}><View style={styles.overlay}><Surface style={styles.confirmModal}><Text style={styles.confirmTitle}>要让它成为正式形态吗？</Text><Text style={styles.copy}>确认后不能选择历史候选替换、不能重新探索，也不能通过直接 API 重捏。以后只能在长期经历中软连续进化。</Text><AppButton label="再看一看" variant="quiet" onPress={() => setConfirming(false)} /><AppButton label="我确认这是它" onPress={confirm} /></Surface></View></Modal>
      <Modal transparent visible={Boolean(correcting)} animationType="fade" onRequestClose={() => setCorrecting(null)}><View style={styles.overlay}><Surface style={styles.confirmModal}><Text style={styles.confirmTitle}>你希望它怎样理解？</Text><Text style={styles.copy}>用你自己的话改写这条观察。之后模型只使用纠正后的表达。</Text><TextInput value={correction} onChangeText={setCorrection} multiline maxLength={1000} style={[styles.input, styles.instruction]} /><AppButton label="取消" variant="quiet" onPress={() => setCorrecting(null)} /><AppButton label="保存纠正" disabled={!correction.trim() || busy} onPress={() => { const signal = correcting; if (!signal) return; void act(async () => { await repository.feedback(signal.id, "corrected", correction.trim()); setCorrecting(null); }); }} /></Surface></View></Modal>
      <Modal transparent visible={evolving} animationType="fade" onRequestClose={() => setEvolving(false)}><View style={styles.overlay}><Surface style={styles.confirmModal}><Text style={styles.confirmTitle}>给它一句祝福</Text><Text style={styles.copy}>你只能表达期待、祝福或赠送象征物，不能指定终态。它会根据确认后的真实经历自主长成下一阶段。</Text><TextInput value={blessing} onChangeText={setBlessing} multiline maxLength={1000} placeholder="例如：愿你继续按自己的方式认识世界" placeholderTextColor={colors.textMuted} style={[styles.input, styles.instruction]} /><AppButton label="先不进化" variant="quiet" onPress={() => setEvolving(false)} /><AppButton label={busy ? "正在长大…" : "送出祝福"} disabled={busy} onPress={() => void evolve()} /></Surface></View></Modal>
    </ScrollView>
  );
}

const styles = StyleSheet.create({
  page: { flex: 1, backgroundColor: colors.canvas }, center: { flex: 1, backgroundColor: colors.canvas, justifyContent: "center" }, content: { width: "100%", maxWidth: 720, alignSelf: "center", paddingHorizontal: spacing.md, paddingBottom: 110, gap: spacing.md }, eyebrow: { color: colors.mint, fontSize: 11, fontWeight: "900", letterSpacing: 1.5 }, title: { color: colors.text, fontSize: 32, fontWeight: "900" },
  naming: { gap: spacing.md }, sectionTitle: { color: colors.text, fontSize: 18, fontWeight: "900" }, copy: { color: colors.textMuted, lineHeight: 21 }, input: { minHeight: 49, borderRadius: radii.md, backgroundColor: colors.surface, color: colors.text, paddingHorizontal: spacing.md, paddingVertical: 12 },
  stage: { gap: spacing.sm }, stageLabel: { color: colors.mint, fontSize: 11, fontWeight: "900", letterSpacing: 1 }, stageTitle: { color: colors.text, fontSize: 20, fontWeight: "900" }, progressTrack: { height: 8, borderRadius: 4, backgroundColor: colors.surface }, progressFill: { height: 8, borderRadius: 4, backgroundColor: colors.coral }, progressText: { color: colors.textMuted, fontSize: 12 },
  visualCard: { gap: spacing.md }, visualHeader: { flexDirection: "row", justifyContent: "space-between", alignItems: "flex-start", gap: spacing.sm }, quota: { color: colors.coralSoft, fontSize: 11, fontWeight: "800" }, visual: { alignItems: "center", minHeight: 260, justifyContent: "center" }, candidates: { gap: 8 }, candidate: { width: 88, padding: 6, borderRadius: 16, backgroundColor: colors.surface, alignItems: "center", borderWidth: 1, borderColor: "transparent", overflow: "hidden" }, candidateSelected: { borderColor: colors.mint }, candidateLabel: { color: colors.textMuted, fontSize: 10 }, instruction: { minHeight: 76, textAlignVertical: "top" }, buttonRow: { flexDirection: "row", gap: 8 }, flex: { flex: 1 },
  confirmed: { alignItems: "stretch", gap: spacing.md }, lineage: { alignSelf: "center", paddingHorizontal: 13, paddingVertical: 7, borderRadius: radii.pill, backgroundColor: colors.mintDeep }, lineageText: { color: colors.mint, fontSize: 12, fontWeight: "800" }, ready: { gap: spacing.md },
  experienceList: { gap: 8 }, experience: { backgroundColor: colors.surface, borderRadius: radii.md, padding: 10, gap: 4 }, experienceText: { color: colors.text, lineHeight: 19 }, repairNote: { color: colors.textMuted, fontSize: 11, textAlign: "center" },
  chatCard: { gap: spacing.md }, chatHead: { flexDirection: "row", justifyContent: "space-between" }, private: { color: colors.mint, fontSize: 11 }, thread: { gap: 8 }, privateMessage: { maxWidth: "82%", borderRadius: 15, padding: 10 }, ownerMessage: { alignSelf: "flex-end", backgroundColor: colors.coralSoft }, petMessage: { alignSelf: "flex-start", backgroundColor: colors.mintDeep }, privateText: { color: colors.text, lineHeight: 20 }, ownerText: { color: colors.textDark }, chatComposer: { flexDirection: "row", alignItems: "flex-end", gap: 8 }, chatInput: { flex: 1, minHeight: 45, maxHeight: 100, backgroundColor: colors.surface, borderRadius: 15, color: colors.text, padding: 11 }, chatSend: { backgroundColor: colors.coral, minHeight: 45, borderRadius: 14, justifyContent: "center", paddingHorizontal: 14 }, chatSendText: { color: colors.white, fontWeight: "900" }, disabled: { opacity: .4 },
  signalSection: { gap: spacing.md }, signal: { gap: 8 }, forgotten: { opacity: .5 }, signalHead: { flexDirection: "row", justifyContent: "space-between" }, signalTitle: { color: colors.text, fontWeight: "900", flex: 1 }, confidence: { color: colors.mint, fontWeight: "800" }, signalBody: { color: colors.text, lineHeight: 20 }, signalSource: { color: colors.textMuted, fontSize: 11 }, signalImpact: { color: colors.lavender, fontSize: 12, lineHeight: 18 }, signalActions: { flexDirection: "row", gap: spacing.lg, marginTop: 4 }, signalAction: { color: colors.textMuted, fontWeight: "800" }, signalActionActive: { color: colors.mint }, forget: { color: colors.coralSoft, fontWeight: "800" },
  error: { backgroundColor: "#603345", borderRadius: radii.md, padding: spacing.sm }, errorText: { color: colors.coralSoft, textAlign: "center" }, overlay: { flex: 1, backgroundColor: "rgba(4,3,13,.78)", alignItems: "center", justifyContent: "center", padding: spacing.lg }, confirmModal: { width: "100%", maxWidth: 480, gap: spacing.md }, confirmTitle: { color: colors.text, fontSize: 22, fontWeight: "900" },
  taskCard: { gap: spacing.md, borderWidth: 1, borderColor: colors.coralSoft }, taskHead: { flexDirection: "row", alignItems: "center", justifyContent: "space-between", gap: spacing.md }, taskInline: { backgroundColor: colors.surface, borderRadius: radii.md, padding: spacing.sm, gap: spacing.sm, alignItems: "center" },
});
