// Live product-model acceptance. Only temporary accounts/groups and synthetic discussion text.
import {createClient} from "npm:@supabase/supabase-js@2";
import {extractGroupWork} from "./model.ts";
const url=Deno.env.get("SUPABASE_URL"),key=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY"),anon=Deno.env.get("SUPABASE_ANON_KEY"),model=Deno.env.get("TEXT_MODEL");
if(!url||!key||!anon||!["127.0.0.1","localhost"].includes(new URL(url).hostname)||new URL(url).port!=="47321")throw new Error("Isolated primary fixture on port 47321 required");
if(!model||!Deno.env.get("TEXT_API_BASE_URL")||!Deno.env.get("TEXT_API_KEY"))throw new Error("Live TEXT_API configuration required");
Deno.env.set("MODEL_MOCK_MODE","false");
const options={auth:{persistSession:false,autoRefreshToken:false}},service=createClient(url,key,options),users:string[]=[],spaces:string[]=[];
const caseNames=["no consent means no collection or model call","real actions and responsibility","jokes are not tasks","hypothetical wishes are not tasks","later cancellation overrides earlier proposal","mixed discussion keeps only grounded actions","continued discussion defers live late result","revoked consent rejects live late result"];
const selectedCases=Deno.env.get("GROUP_WORK_LIVE_CASES")?.split("|");
if(selectedCases?.some(name=>!caseNames.includes(name)))throw new Error("Unknown live acceptance case");
async function sourceHash(path:string){return Array.from(new Uint8Array(await crypto.subtle.digest("SHA-256",await Deno.readFile(path)))).map(value=>value.toString(16).padStart(2,"0")).join("");}
const sourceHashes={model:await sourceHash("supabase/functions/group-work-suggestions/model.ts"),liveTest:await sourceHash("supabase/functions/group-work-suggestions/live.test.ts")};
const results:any[]=[];let checks=0;const cleanup:{status:string;spaces:number;users:number;errors:string[]}={status:"pending",spaces:0,users:0,errors:[]};
function ok(result:any):any{if(result.error)throw new Error(result.error.message);return result.data;}
function assert(value:unknown,label:string){if(!value)throw new Error(label);checks++;}
async function rpc(name:string,args:any){return ok(await service.rpc(name,args));}
async function user(label:string){const email=`group-model-${crypto.randomUUID()}@example.test`,password=`Group-${crypto.randomUUID()}-1!`,id=ok(await service.auth.admin.createUser({email,password,email_confirm:true})).user.id;users.push(id);ok(await service.from("profiles").insert({id,email,nickname:label}));const client=createClient(url!,anon!,options);ok(await client.auth.signInWithPassword({email,password}));return{id,client};}
async function check(name:string,run:(record:any)=>Promise<void>){if(selectedCases&&!selectedCases.includes(name))return;const record:any={name,status:"running",model};const began=Date.now();try{await run(record);record.status="passed";console.log(`PASS live group: ${name}`);}catch(reason){record.status="failed";record.error=String(reason instanceof Error?reason.message:reason).slice(0,500);console.log(`FAIL live group: ${name}: ${record.error}`);}finally{record.totalMs=Date.now()-began;results.push(record);await save();}}
async function save(){await Deno.mkdir("test-results/group-work-live-model",{recursive:true});await Deno.writeTextFile("test-results/group-work-live-model/report.json",JSON.stringify({generatedAt:new Date().toISOString(),model,fixture:url,sourceHashes,expectedCaseCount:caseNames.length,selectedCases:selectedCases??caseNames,fullSuite:results.length===caseNames.length,checks,leaseMode:"Only each synthetic batch receives a controlled test lease. Global claim/sweep is never invoked; this is not new claim acceptance.",cleanup,results},null,2));}
try{
 const A=await user("群模型验收小周"),B=await user("群模型验收阿林");
 async function group(name:string){const space=ok(await service.from("spaces").insert({name:`合成讨论${spaces.length+1}-${name.slice(0,12)}`,kind:"friend_circle",created_by:A.id}).select("id").single());spaces.push(space.id);ok(await service.from("space_members").insert([{space_id:space.id,user_id:A.id,role:"owner"},{space_id:space.id,user_id:B.id,role:"member"}]));return space.id as string;}
 async function authorization(sid:string){return ok(await service.from("group_work_authorizations").select("*").eq("space_id",sid).single());}
 async function consent(sid:string,actor:any,yes=true){const a=await authorization(sid);return rpc("set_group_work_consent",{p_actor:actor.id,p_space:sid,p_version:a.version,p_consented:yes});}
 async function say(sid:string,actor:any,text:string){return ok(await actor.client.from("messages").insert({client_id:crypto.randomUUID(),space_id:sid,sender_id:actor.id,actor_kind:"human",actor_name:"合成成员",kind:"text",text}).select("id,text,sender_id,created_at").single());}
 async function batches(sid:string){return ok(await service.from("group_work_batches").select("*").eq("space_id",sid).order("created_at"));}
 async function ready(sid:string,texts:readonly string[]){await consent(sid,A);await consent(sid,B);const sources=[];for(let i=0;i<texts.length;i++)sources.push(await say(sid,i%2?B:A,texts[i]));const batch=(await batches(sid)).find((row:any)=>row.status==="queued");assert(Boolean(batch),"authorized synthetic discussion creates a batch");assert(Date.parse(batch.ready_at)>=Date.now()+175000,"batch waits about three minutes after latest message");const token=crypto.randomUUID();ok(await service.from("group_work_batches").update({status:"running",lease_token:token,lease_until:new Date(Date.now()+180000).toISOString(),attempts:1}).eq("id",batch.id).eq("space_id",sid).eq("status","queued").select("id").single());return{sources,batch:{...batch,lease_token:token}};}
 async function finish(batch:any,suggestions:any[]){return rpc("finish_group_work_batch",{p_batch:batch.id,p_token:batch.lease_token,p_suggestions:suggestions,p_error:null});}
 async function counts(sid:string){return{suggestions:ok(await service.from("group_work_suggestions").select("id,title,description,sources,invalidated").eq("space_id",sid)),items:ok(await service.from("work_items").select("id").eq("space_id",sid))};}
 function validSources(sources:any[],suggestions:any[]){const lookup=new Map(sources.map(source=>[source.id,source.text]));assert(suggestions.every(s=>s.sources.length&&s.sources.every((ref:any)=>lookup.has(ref.message_id)&&lookup.get(ref.message_id).includes(ref.quote))),"every model quote is an exact fragment of a supplied source");}
 async function extract(record:any,sources:any[]){record.sources=sources;record.modelCalls=1;const started=Date.now();try{const suggestions=await extractGroupWork(sources);record.modelMs=Date.now()-started;record.suggestions=suggestions;validSources(sources,suggestions);return suggestions;}catch(reason){record.modelMs=Date.now()-started;throw reason;}}
 await check("no consent means no collection or model call",async record=>{const sid=await group("未授权");await say(sid,A,"我来整理活动报名表，今晚发群里。");assert((await batches(sid)).length===0,"no batch before consent");await consent(sid,A);await say(sid,B,"我来带两筒羽毛球。");assert((await batches(sid)).length===0,"one member consent cannot enable collection");record.modelCalls=0;});
 const cases=[
  {name:"real actions and responsibility",texts:["这周聚餐的菜单还没定。阿林，你来整理大家忌口，周五下午发群里，可以吗？","可以，我来整理大家的忌口，周五下午发到群里。","我负责订桌，周四晚上之前告诉大家结果。"],topics:[/忌口/,/订桌|订位|餐桌|餐厅/],responsibilitySources:[1,2],empty:false},
  {name:"jokes are not tasks",texts:["明天我带大家坐火箭去火星开会，哈哈开玩笑的。","哈哈，火星出差记得报销，纯属玩笑。"],topics:[],empty:true},
  {name:"hypothetical wishes are not tasks",texts:["如果以后攒够钱，也许可以包下一座海岛办年会。","先假设一下而已，现在没决定也没有安排。"],topics:[],empty:true},
  {name:"later cancellation overrides earlier proposal",texts:["周六一起骑车去山顶吧，我可以先查路线。","周六有暴雨，这个骑行计划取消，不查路线不出发。","好，取消，先不安排这件事了。"],topics:[],empty:true},
  {name:"mixed discussion keeps only grounded actions",texts:["我来确认周六羽毛球场地，今晚把是否订到发群里。","要是下雨，我们就建一个室内体育馆，开玩笑啦。","刚才说的周日爬山已经取消，别再安排。","羽毛球要用的球我来带两筒。"],topics:[/场地|球场/,/两筒|带球|羽毛球.*球|准备.*球/],responsibilitySources:[0,3],empty:false},
 ];
 for(const sample of cases)await check(sample.name,async record=>{const sid=await group(sample.name),{sources,batch}=await ready(sid,sample.texts);const suggestions=await extract(record,sources);if(sample.empty)assert(suggestions.length===0,"jokes/hypotheses/cancelled plans must yield no suggestion");else{assert(suggestions.length===2,"two independent real actions yield two suggestions");const matches=sample.topics.map((pattern,index)=>suggestions.find(s=>pattern.test(`${s.title} ${s.description}`)&&s.sources.some(ref=>ref.message_id===sources[sample.responsibilitySources![index]].id&&/我来|我负责/.test(ref.quote))));for(let index=0;index<matches.length;index++)assert(Boolean(matches[index]),`grounded action ${sample.topics[index]} retains its own responsibility quote`);assert(new Set(matches).size===2,"different members' responsibilities remain separate suggestions");if(sample.name.startsWith("mixed"))assert(!suggestions.some(s=>/爬山|体育馆|下雨/.test(`${s.title} ${s.description}`)),"cancelled and joking plans never become suggested actions");}record.committed=await finish(batch,suggestions);assert(record.committed===true,"real model output passes transactional source validation");const saved=await counts(sid);assert(saved.suggestions.length===suggestions.length,"database retains exactly the accepted model suggestions");assert(saved.items.length===0,"model suggestions never create formal work before a person accepts");});
 await check("continued discussion defers live late result",async record=>{const sid=await group("持续讨论"),{sources,batch}=await ready(sid,["我来整理社区活动报名表，今晚发到群里。"]);const pending=extract(record,sources);const resumed=await say(sid,B,"活动场地还没确定，先继续讨论，别发安排。");const suggestions=await pending;assert(suggestions.length>0,"live model produced the initial grounded action");record.committed=await finish(batch,suggestions);assert(record.committed===false,"new discussion before commit defers live result");const queued=(await batches(sid)).find((b:any)=>b.status==="queued");assert(Boolean(queued)&&Date.parse(queued.from_at)<=Date.parse(batch.from_at)&&Date.parse(queued.through_at)>=Date.parse(resumed.created_at),"new batch folds the whole earlier range into resumed discussion");assert(Date.parse(queued.ready_at)>=Date.parse(resumed.created_at)+175000,"resumed discussion resets three-minute quiet period");assert((await counts(sid)).suggestions.length===0,"deferred live result never inserts an early group suggestion");});
 await check("revoked consent rejects live late result",async record=>{const sid=await group("撤权迟到"),{sources,batch}=await ready(sid,["我负责打印活动签到表，周五晚上完成。"]);const pending=extract(record,sources);await consent(sid,B,false);const suggestions=await pending;assert(suggestions.length>0,"live model produced grounded action before late commit");record.committed=await finish(batch,suggestions);assert(record.committed===false,"withdrawn authorization prevents live output commit");const a=await authorization(sid);assert(a.active_since===null&&a.version>batch.authorization_version,"authorization version was invalidated");await say(sid,A,"后续消息不能继续分析。");assert((await batches(sid)).every((b:any)=>b.status==="invalidated"),"revoked group does not register further analysis");const saved=await counts(sid);assert(saved.suggestions.length===0&&saved.items.length===0,"late revoked output creates neither suggestion nor task");});
}finally{await save();for(const id of spaces)try{ok(await service.from("spaces").delete().eq("id",id));cleanup.spaces++;}catch{cleanup.errors.push(`space cleanup failed: ${id}`);}for(const id of users)try{ok(await service.auth.admin.deleteUser(id));cleanup.users++;}catch{cleanup.errors.push(`user cleanup failed: ${id}`);}cleanup.status=cleanup.errors.length?"failed":"passed";await save();}
console.log(`Live group model: ${results.filter(r=>r.status==="passed").length}/${results.length} cases; ${checks} assertions. Model: ${model}.`);
if(results.some(record=>record.status!=="passed")||cleanup.status!=="passed")Deno.exit(1);
