import {extractGroupWork} from "./model.ts";
const source={id:"d3ab45fe-e954-4fd8-a1a3-f68e61766a79",sender_id:"42b0d9d7-77c1-408a-b6d3-a1db1c6dc177",text:"我来整理报名表。",created_at:"2026-09-11T09:00:00Z"};
const otherSource={id:"8f632056-012d-45ce-80af-d1c5e41b6de3",sender_id:"e570a2dc-a510-42fe-b579-a01b038767b1",text:"我负责打印签到表，周五晚上完成。",created_at:"2026-09-11T09:00:01Z"};
const suggestion=(id:string,quote=source.text)=>({suggestions:[{title:"整理报名表",description:"本人提出负责，仍需确认",sources:[{message_id:id,quote}]}]});
function assert(value:unknown,message:string){if(!value)throw new Error(message);}
async function fixture(result:unknown,run:(body:()=>any)=>Promise<void>,finishReason="stop"){const names=["MODEL_MOCK_MODE","TEXT_API_BASE_URL","TEXT_API_KEY","TEXT_MODEL"],previous=names.map(name=>Deno.env.get(name)),originalFetch=globalThis.fetch;let body:any;
 try{Deno.env.set("MODEL_MOCK_MODE","false");Deno.env.set("TEXT_API_BASE_URL","https://fixture.invalid/v1");Deno.env.set("TEXT_API_KEY","synthetic-test-only");Deno.env.set("TEXT_MODEL","synthetic-model");globalThis.fetch=async(_request,init)=>{body=JSON.parse(String(init?.body));return new Response(JSON.stringify({choices:[{finish_reason:finishReason,message:{content:JSON.stringify(result)}}]}),{headers:{"Content-Type":"application/json"}});};await run(()=>body);}
 finally{globalThis.fetch=originalFetch;names.forEach((name,index)=>previous[index]===undefined?Deno.env.delete(name):Deno.env.set(name,previous[index]!));}
}
Deno.test("short model references map to canonical source IDs without asking the model to copy UUIDs",async()=>fixture(suggestion("m1"),async body=>{const result=await extractGroupWork([source]);assert(result[0].sources[0].message_id===source.id,"canonical message ID must be server supplied");const input=JSON.parse(body().messages.at(-1).content);assert(input[0].id==="m1"&&!JSON.stringify(input).includes(source.id),"model input uses a short reference only");}));
Deno.test("unknown model reference cannot invent a source",async()=>fixture(suggestion("m2"),async()=>{let failed=false;try{await extractGroupWork([source]);}catch(reason){failed=reason instanceof Error&&reason.message==="work_invalid_model_source";}assert(failed,"unknown reference must fail before SQL commit");}));
Deno.test("a valid reference cannot attribute a fabricated or paraphrased quote",async()=>fixture(suggestion("m1","我来完成所有人的事情。"),async()=>{let failed=false;try{await extractGroupWork([source]);}catch(reason){failed=reason instanceof Error&&reason.message==="work_invalid_model_source";}assert(failed,"non-verbatim quote must fail before SQL commit");}));
async function rejects(sources:readonly typeof source[],expected:string){let failure:unknown;try{await extractGroupWork(sources);}catch(reason){failure=reason;}assert(failure instanceof Error&&failure.message===expected,`must reject the entire result with ${expected}`);}
Deno.test("multiple references preserve each canonical message and sender boundary",async()=>fixture({suggestions:[...suggestion("m2",otherSource.text).suggestions,...suggestion("m1").suggestions]},async()=>{const result=await extractGroupWork([source,otherSource]);assert(result[0].sources[0].message_id===otherSource.id&&result[1].sources[0].message_id===source.id,"references must resolve independently of output order");}));
Deno.test("a quote from another supplied message cannot be reassigned to a valid reference",async()=>fixture(suggestion("m1",otherSource.text),async()=>await rejects([source,otherSource],"work_invalid_model_source")));
Deno.test("separate pieces of a real source cannot be stitched into a quote",async()=>fixture(suggestion("m1","我负责打印签到表周五晚上完成。"),async()=>await rejects([otherSource],"work_invalid_model_source")));
Deno.test("one invalid source rejects all suggestions including otherwise valid ones",async()=>fixture({suggestions:[...suggestion("m1").suggestions,...suggestion("m2").suggestions]},async()=>await rejects([source],"work_invalid_model_source")));
for(const invalidId of [source.id,source.sender_id,"m0","m01","m-1"])Deno.test(`non-reference source ID ${invalidId} fails closed`,async()=>fixture(suggestion(invalidId),async()=>await rejects([source],"text_model_invalid_structure")));
Deno.test("empty evidence cannot produce a suggestion",async()=>fixture({suggestions:[{title:"整理报名表",sources:[]}]},async()=>await rejects([source],"text_model_invalid_structure")));
Deno.test("whitespace-only evidence cannot produce a suggestion",async()=>fixture(suggestion("m1","   "),async()=>await rejects([source],"text_model_invalid_structure")));
Deno.test("truncated output cannot publish even a complete-looking suggestion",async()=>fixture(suggestion("m1"),async()=>await rejects([source],"text_model_output_truncated"),"length"));
