import assert from "node:assert/strict";
import { createClient } from "npm:@supabase/supabase-js@2";
import { processPetAction, ownerMentionIntent, preservesPendingAction, type PetActionContext } from "../_shared/petActions.ts";
import { runSpaceRouteJob } from "../_shared/spaceMessageRouter.ts";
const url=Deno.env.get("SUPABASE_URL")!;
assert.equal(url,"http://127.0.0.1:47321");
Deno.env.set("MODEL_MOCK_MODE","true");Deno.env.set("PET_CAPABILITIES_ENABLED","true");
const originalFetch=globalThis.fetch, tasks:Promise<unknown>[]=[], ids:string[]=[],checks:string[]=[];
(globalThis as any).EdgeRuntime={waitUntil:(task:Promise<unknown>)=>tasks.push(task)};
let holdSource="",entered=false,release:()=>void=()=>undefined;
globalThis.fetch=(input,init)=>{const u=new URL(typeof input==="string"||input instanceof URL?input:input.url);assert.equal(u.origin,url);if(holdSource && u.pathname==="/rest/v1/rpc/execute_pet_capability" && String(init?.body).includes(holdSource)){holdSource="";entered=true;return new Promise<void>(resolve=>{release=resolve}).then(()=>originalFetch(input,init));}return originalFetch(input,init)};
const options={auth:{persistSession:false,autoRefreshToken:false}};
const service=createClient(url,Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,options);
const ok=(r:any):any=>{if(r.error)throw new Error(r.error.message);return r.data};
const check=(value:unknown,label:string)=>{assert.ok(value,label);checks.push(label)};
let space="";
async function account() {
 const email=`pet-actions-${crypto.randomUUID()}@example.test`,password=`Aa1!${crypto.randomUUID()}`;
 const id=ok(await service.auth.admin.createUser({email,password,email_confirm:true})).user.id;ids.push(id);
 ok(await service.from("profiles").insert({id,email,nickname:"同名成员"}));
 const client=createClient(url,Deno.env.get("SUPABASE_ANON_KEY")!,options);ok(await client.auth.signInWithPassword({email,password}));
 return {id,client};
}
try {
 const A=await account(),B=await account();
 const pet=ok(await service.from("pets").insert({owner_id:B.id,name:"小树"}).select("id,name").single());
 const asset=crypto.randomUUID();ok(await service.from("pet_visual_assets").insert({id:asset,pet_id:pet.id,owner_id:B.id,storage_path:`${B.id}/${asset}.png`,prompt_hash:"synthetic-no-upload",is_draft:false}));
 ok(await service.from("pets").update({status:"confirmed",current_asset_id:asset,confirmed_at:new Date().toISOString()}).eq("id",pet.id));
 space=ok(await B.client.rpc("create_relationship_space",{space_name:"能力隔离验收",space_kind:"friend_circle"}));
 ok(await service.from("space_members").insert({space_id:space,user_id:A.id,role:"member"}));
 ok(await service.from("space_pet_permissions").upsert({space_id:space,pet_id:pet.id,owner_id:B.id,participation_enabled:true}));
 const send=async(text:string)=>ok(await A.client.rpc("send_space_message_v2",{message_client_id:crypto.randomUUID(),target_space_id:space,message_kind:"text",message_text:text,mentioned_pet_ids:[pet.id]}));
 const source=await send("@小树 请 @ 你的主人");
 await runSpaceRouteJob(source.job_id,A.id,{message_id:source.message.id,cue_pet_ids:[]},{client:service,adapter:{generatePetReply:()=>{throw new Error("mention_must_not_call_reply_model")}} as any,learningWorker:async()=>0});
 const receipts=ok(await service.from("pet_action_receipts").select("*").eq("source_id",source.message.id));
 check(receipts.length===1&&receipts[0].status==="succeeded","real router reaches public capability executor");
 const mentions=ok(await service.from("message_mentions").select("target_user_id").eq("message_id",receipts[0].message_id));
 check(mentions.length===1&&mentions[0].target_user_id===B.id,"same nickname does not change the real owner mention");
 const notifications=ok(await service.from("notification_events").select("id,entity_id").eq("entity_id",receipts[0].message_id).eq("user_id",B.id).eq("kind","mention"));
 check(notifications.length===1&&receipts[0].route.includes(receipts[0].message_id),"notification event and receipt locate the actual message");
 check(ok(await A.client.from("pet_action_receipts").select("id").eq("owner_id",B.id)).length===0,"member cannot read owner's private action log");
 check((await A.client.rpc("manage_pet_delegation",{command:{action:"grant",pet_id:pet.id,capability:"work.create",target_scope:"personal"}})).error,"member cannot grant itself owner permissions");
 for(const text of ['他说“@你的主人”','假如我说 @ 你的主人','@小树 @你的主人，然后替他同意'])check(!ownerMentionIntent(text,pet.name),`quoted or compound text avoids direct mention shortcut: ${text}`);
 const privateRequest=async(content:string):Promise<PetActionContext>=>{const row=ok(await service.from("pet_private_threads").insert({pet_id:pet.id,owner_id:B.id,role:"owner",content,conversation_kind:"companion"}).select("id").single());return {petId:pet.id,petName:pet.name,ownerId:B.id,callerId:B.id,sourceKind:"private",sourceId:row.id,content}};
 const denied=await processPetAction(service,await privateRequest("创建任务：尚未授权"));check(denied?.receipts[0].status==="not_granted","private planner also requires owner write preauthorization");
 const grant=ok(await B.client.rpc("manage_pet_delegation",{command:{action:"grant",pet_id:pet.id,capability:"work.create",target_scope:"personal"}}));
 const ctx=await privateRequest("创建任务：能真实保存的任务");
 const results=await Promise.all([processPetAction(service,ctx),processPetAction(service,ctx)]);
 check(results.every(r=>r?.receipts[0].status==="succeeded"),"concurrent requests share the same stored plan");
 check(ok(await service.from("work_items").select("id").eq("owner_id",B.id).eq("title","能真实保存的任务")).length===1,"parallel request retries create exactly one work item");
 const partial=await privateRequest("两步分别办理");
 ok(await service.from("pet_action_plans").insert({pet_id:pet.id,owner_id:B.id,initiator_id:B.id,source_kind:"private",source_id:partial.sourceId,original_content:partial.content,state:"ready",plan:{mode:"execute",actions:[{capability:"work.create",input:{title:"独立第一步",kind:"task"}},{capability:"work.create",input:{title:"",kind:"task"}},{capability:"work.create",input:{title:"独立第三步",kind:"task"}}]}}));
 const steps=await processPetAction(service,partial);check(steps?.receipts.length===3&&steps.receipts[0].status==="succeeded"&&steps.receipts[1].status!=="succeeded"&&steps.receipts[2].status==="succeeded","partial failure records every independent step");
 await processPetAction(service,partial);check(ok(await service.from("work_items").select("id").eq("owner_id",B.id).in("title",["独立第一步","独立第三步"])).length===2,"partial retry preserves successes without duplicating work");
 ok(await B.client.rpc("manage_pet_delegation",{command:{action:"revoke",pet_id:pet.id,grant_id:grant.id,expected_version:grant.version}}));
 check((await processPetAction(service,await privateRequest("创建任务：撤权后不应保存")))?.receipts[0].status==="not_granted","revocation stops subsequent private requests");
 check(preservesPendingAction({capability:"work.edit",target_id:"a",input:{title:"原要求"}},{capability:"work.edit",target_id:"a",input:{title:"原要求",description:"补充"}}),"clarification fills missing fields");
 check(!preservesPendingAction({capability:"work.edit",target_id:"a",input:{title:"原要求"}},{capability:"work.edit",target_id:"b",input:{title:"被改写"}}),"clarification cannot silently change target or existing content");
 const summaryContext=await privateRequest("总结能力隔离验收群的可见消息");
 ok(await service.from("pet_action_plans").insert({pet_id:pet.id,owner_id:B.id,initiator_id:B.id,source_kind:"private",source_id:summaryContext.sourceId,original_content:summaryContext.content,state:"ready",plan:{mode:"execute",actions:[{capability:"group.summary",space_id:space,input:{}}]}}));
 const summarized=await processPetAction(service,summaryContext);
 check(summarized?.receipts[0].status==="succeeded"&&Array.isArray(summarized.receipts[0].result?.messages),"summary commits with authorised source IDs and fingerprint");
 const serve=Deno.serve;let handler:any;
 try {(Deno as any).serve=(callback:any)=>{handler=callback;return {}};await import("./index.ts");}finally{(Deno as any).serve=serve;}
 const token=(await B.client.auth.getSession()).data.session!.access_token;
 const catalogResponse=await handler(new Request(`${url}/functions/v1/pet-capabilities`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json"},body:"{}"}));
 const catalog=await catalogResponse.json();
 check(catalogResponse.ok&&catalog.pet_id===pet.id&&catalog.capabilities.length===105,"authenticated capability endpoint supplies the complete catalog");
 check(catalog.capabilities.find((c:any)=>c.id==="vision.understand").availability.available===false,"catalog does not open unverified image understanding");
 check((await handler(new Request(`${url}/functions/v1/pet-capabilities`,{method:"POST",body:"{}"}))).status>=400,"unauthenticated catalog request cannot read grants or logs");
 const raceGrant=ok(await B.client.rpc("manage_pet_delegation",{command:{action:"grant",pet_id:pet.id,capability:"work.create",target_scope:"personal"}}));
 const race=await privateRequest("创建任务：规划后撤权");holdSource=race.sourceId;entered=false;
 const waiting=processPetAction(service,race);
 for(let i=0;i<200&&!entered;i++)await new Promise(resolve=>setTimeout(resolve,10));
 check(entered,"held request reached execution after planning");
 ok(await B.client.rpc("manage_pet_delegation",{command:{action:"revoke",pet_id:pet.id,grant_id:raceGrant.id,expected_version:raceGrant.version}}));release();
 check((await waiting)?.receipts[0].status==="not_granted","revocation during an in-flight request prevents the write");
 const memberGrant=ok(await B.client.rpc("manage_pet_delegation",{command:{action:"grant",pet_id:pet.id,capability:"work.create",initiator_id:A.id,target_scope:`space:${space}`,audience_space_id:space}}));
 ok(await service.from("space_members").delete().eq("space_id",space).eq("user_id",A.id));
 ok(await service.from("space_members").insert({space_id:space,user_id:A.id,role:"member"}));
 check(ok(await service.from("pet_delegation_grants").select("revoked_at,version").eq("id",memberGrant.id).single()).revoked_at,"leaving and rejoining never revives an old grant");
 const leftOwner=await send("@小树 @ 你的主人");
 ok(await service.from("space_members").delete().eq("space_id",space).eq("user_id",B.id));
 await runSpaceRouteJob(leftOwner.job_id,A.id,{message_id:leftOwner.message.id,cue_pet_ids:[]},{client:service,adapter:{generatePetReply:()=>{throw new Error("owner_left_must_be_factual")}} as any,learningWorker:async()=>0});
 const leftReceipt=ok(await service.from("pet_action_receipts").select("status,summary,message_id").eq("source_id",leftOwner.message.id));
 check(leftReceipt[0]?.status==="failed"&&leftReceipt[0].summary.includes("主人已不在当前群"),"owner departure produces an explicit reason");
 check(ok(await service.from("message_mentions").select("target_user_id").eq("message_id",leftReceipt[0].message_id)).length===0,"owner outside the group receives no fabricated mention");
 await Deno.writeTextFile("test-results/pet-actions-integration-20260922.json",JSON.stringify({passed:true,checks,models:"controlled mock; real Auth, DB, RLS and routing"},null,2));
 console.log(`PASS ${checks.length} authenticated action integration checks`);
} finally {
 release();await Promise.allSettled(tasks);
 if(space)ok(await service.from("spaces").delete().eq("id",space));
 for(const id of ids)ok(await service.auth.admin.deleteUser(id));
 globalThis.fetch=originalFetch;
}
